cam_width:  640
cam_height: 640
cam_fx:     897.0
cam_fy:     908.6
cam_cx:     316.6
cam_cy:     279.5

cam2body_R: [ 0.0,  -1.0,  1.0,
             -1.0,  0.0,  0.0,
              0.0, 0.0,  -1.0]
cam2body_p: [0.12, 0.0, -0.22]
